export const indianSubjects = [
  // Core Subjects
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Science",
  "Environmental Science",
  "Computer Science",
  "Information Technology",
  "Artificial Intelligence",
  "Data Science",
  
  // Languages (Common in India)
  "English",
  "Hindi",
  "Sanskrit",
  "Urdu",
  "Punjabi",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Gujarati",
  "Marathi",
  "Bengali",
  "Odia",
  "Assamese",
  "Kashmiri",
  "Nepali",
  "French",
  "German",
  "Spanish",
  "Arabic",
  
  // Social Studies
  "History",
  "Geography",
  "Political Science",
  "Civics",
  "Economics",
  "Sociology",
  "Psychology",
  "Philosophy",
  "Public Administration",
  "Anthropology",
  
  // Commerce Stream
  "Accountancy",
  "Business Studies",
  "Business Administration",
  "Entrepreneurship",
  "Financial Accounting",
  "Corporate Law",
  "Cost Accounting",
  "Taxation",
  "Banking",
  "Marketing",
  
  // Arts & Humanities
  "Fine Arts",
  "Music",
  "Dance",
  "Theatre Studies",
  "Home Science",
  "Fashion Designing",
  "Journalism",
  "Mass Communication",
  "Library Science",
  
  // Technical / Vocational
  "Mechanical Engineering",
  "Civil Engineering",
  "Electrical Engineering",
  "Electronics",
  "Automobile Engineering",
  "Agriculture",
  "Agricultural Science",
  "Biotechnology",
  "Microbiology",
  "Environmental Engineering",
  
  // Health & Medical
  "General Medicine",
  "Nursing",
  "Pharmacy",
  "Anatomy",
  "Physiology",
  "Zoology",
  "Botany",
  
  // Competitive Exam Related
  "General Knowledge",
  "General Studies",
  "Current Affairs",
  "Logical Reasoning",
  "Quantitative Aptitude",
  "Verbal Ability",
  "Data Interpretation",
  "Ethics",
  
  // Physical & Others
  "Physical Education",
  "Yoga",
  "Disaster Management",
  "Value Education",
  "Moral Science",
  "Work Education"
];